#!/bin/csh -f
#
if( $#argv == 0 ) then
  echo 'Usage: sh_cc2nocc <list of rinex files>'
  exit
endif
#

foreach rx ($argv)
   echo -n 'Converting '$rx
   \mv $rx $rx.org
   cc2noncc $rx.org $rx
   if ( ! -e $rx ) then
     echo ' Conversion not needed'
     \mv $rx.org $rx
   else
     echo ' Conversion complete'
   endif
end
