#!/bin/csh -f
#
#doc Scan and summarize list of rinex files given
#doc
#
# Modified for most cases S. McClusky 97/02/21
if ($#argv == 0) then
   echo ' '                                       
   echo ' Scan RINEX files'
   echo ' '
   echo ' examples'                               
   echo ' '                                       
   echo '   sh_rxscan vndn1230.90o'
   echo '   sh_rxscan *.90o'
   echo '   sh_rxscan *.90o doc'
   echo '   sh_rxscan ankm*.90o mele*.90o kara*.90o  doc'
   echo ' '                                       
   echo ' where the doc option will create .doc files'                               
   echo ' '                                       
   echo ' '                                       
exit
else 
endif 

set  extend_doc  = no 
set files = ""
foreach i ( `echo $argv` ) 
#old	if ( `echo $i | cut -c12- ` == o) then 
	if ( `echo $i | awk '{FS="/"} {print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10}' | awk '{print $(NF)}' | cut -c12- ` == o) then 
		set files = ( $files $i ) 
	else 
		set  extend_doc = yes
	endif
end


# loop over all files
foreach file ( `echo $files ` )
   echo 'Working on ' $file    
# Check for DOS format rinex files convert to UNIX if necessary                        
  set num = `head -n 1  $file | od -c | grep '\\r' | wc -l `
        # Modified by M. Floyd (2011/06/10, MIT)
        # to use tr instead of potentially unavailable dos2unix
        #if ( $num != 0 ) dos2unix $file $file
        if ( $num != 0 ) then
          tr -d '\r' < $file > $file.tmp && mv -f $file.tmp $file
        endif
  echo 'Converting RINEX file from DOS to UNIX end-of-line'

# output to screen
if ( $extend_doc == no ) then
rxscan <<[
$file
[

else
# output to .doc file
rxscan  >! $file.doc <<[
$file
[
endif

end # foreach




